// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen entrypoint --dispatch).

import { Context, connection, getRegisteredClass } from "@dagger.io/dagger"
import { __loadObject as __loadCoreObject } from "./clients/loader.gen.js"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { HelloWorld } from "./src/index"

function rebuildHelloWorld(state: any): HelloWorld {
  const __obj = Object.assign(Object.create(HelloWorld.prototype), state ?? {})
  if (state) {
  }
  return __obj
}

async function serializeHelloWorld(__obj: HelloWorld): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  return __state
}



async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "HelloWorld": {
      switch (fnName) {

        case "": {
          const __result = new HelloWorld()
          return await serializeHelloWorld(__result)
        }

        case "helloWorld": {
          const __parent = rebuildHelloWorld(parentJson)
          const __result = await __parent.helloWorld()
          return __result
        }
        default:
          throw new Error(`unknown function ${fnName} on HelloWorld`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

type CallRequest = {
  receiverType: string
  receiverValue: string | null
  fnName: string
  fnArgs: string
}

async function readStdin(): Promise<string> {
  const chunks: Buffer[] = []
  for await (const chunk of process.stdin) {
    chunks.push(Buffer.from(chunk))
  }
  return Buffer.concat(chunks).toString("utf8")
}

// receiverValue and fnArgs arrive as JSON *strings*, not as embedded objects: the
// Dang entrypoint builds the request with JSON.encode, which serializes a JSON
// scalar to a string. So each is decoded a second time here.
function decodeRequest(raw: string): {
  receiverType: string
  fnName: string
  parentJson: any
  args: Record<string, any>
} {
  const request = JSON.parse(raw) as CallRequest
  return {
    receiverType: request.receiverType,
    fnName: request.fnName,
    parentJson:
      request.receiverValue === null || request.receiverValue === undefined
        ? null
        : JSON.parse(request.receiverValue),
    args: JSON.parse(request.fnArgs ?? "{}") as Record<string, any>,
  }
}

async function engineCall(): Promise<void> {
  const { receiverType, fnName, parentJson, args } = decodeRequest(await readStdin())

  await connection(
    async () => {
      // No serve here: a module is only ever reached through a `dag.<module>()`
      // call, and each generated client serves its own module before its first
      // query.
      const result = await invoke(receiverType, fnName, parentJson, args)
      process.stdout.write(
        result === undefined || result === null ? "null" : JSON.stringify(result),
      )
    },
    // stdout is the result channel now, so the session's logs go to stderr. The
    // engine reads one and streams the other; crossing them corrupts the result.
    { LogOutput: process.stderr },
  )
}

// The mode is checked rather than ignored so that a stale entrypoint — one
// generated against a different protocol — fails here with something readable
// instead of hanging on a stdin that never arrives.
async function main(): Promise<void> {
  const mode = process.argv[2]
  if (mode !== "engine-call") {
    throw new Error(`unknown mode ${JSON.stringify(mode ?? "")}; want "engine-call"`)
  }
  return engineCall()
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})