/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
import { Context, BaseClient } from "@dagger.io/dagger"
import { dag as __dag } from "@dagger.io/dagger"
import {
  Container
} from "@dagger.io/dagger"
import type {
  ID
} from "@dagger.io/dagger"


export type HelloHelloOpts = {
  /**
   * Change the greeting
   */
  greeting?: string // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L26)

  /**
   * Change the name
   */
  name?: string // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L30)

  /**
   * Encode the message in giant multi-character letters
   */
  giant?: boolean // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L33)

  /**
   * Make the message uppercase, and add more exclamation points
   */
  shout?: boolean // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L36)

  /**
   * Custom container for running the figlet tool
   */
  figletContainer?: Container // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L39)
}

/**
 * A Dagger module to say hello to the world!
 */
export class Hello extends BaseClient { // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L19)
  private readonly _id?: ID | undefined = undefined
  private readonly _hello?: string | undefined = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
     _hello?: string,
   ) {
     super(ctx)

     this._id = _id
     this._hello = _hello
   }

  /**
   * A unique identifier for this Hello.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }

  /**
   * Say hello to the world!
   * @param opts.greeting Change the greeting
   * @param opts.name Change the name
   * @param opts.giant Encode the message in giant multi-character letters
   * @param opts.shout Make the message uppercase, and add more exclamation points
   * @param opts.figletContainer Custom container for running the figlet tool
   */
  hello = async (
    opts?: HelloHelloOpts // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L22) 
    ): Promise<string> => { // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L22)
    if (this._hello) {
      return this._hello
    }

    const ctx = this._ctx.select(
      "hello",
      { ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
}

/**
 * The root of the DAG.
 */
export class Client extends BaseClient {

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
   ) {
     super(ctx)

   }

  /**
   * Get the Raw GraphQL client.
   */
  public getGQLClient() {
    return this._ctx.getGQLClient()
  }

  /**
   * A Dagger module to say hello to the world!
   */
  hello = (): Hello => { // hello (https://github.com/shykes/daggerverse/tree/f82c283510bac0399451dff7ffbec0274bfc3bd4/hello/main.go#L19)

    const ctx = this._ctx.select(
      "hello",
    )
    return new Hello(ctx)
  }
}



async function __serveModule(): Promise<void> {
  await __dag.serveModule("github.com/shykes/daggerverse/hello@f82c283510bac0399451dff7ffbec0274bfc3bd4", { refPin: "f82c283510bac0399451dff7ffbec0274bfc3bd4" })
}

export const dag = new Client(
  new Context().withServe({ key: "hello", run: __serveModule }),
)
export function hello(): Hello {
  return dag.hello()
}
