/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
import { Context, BaseClient } from "@dagger.io/dagger"
import { dag as __dag } from "@dagger.io/dagger"
import {
  Directory,
  Secret
} from "@dagger.io/dagger"
import type {
  ID
} from "@dagger.io/dagger"



export class Repro extends BaseClient { // repro (../typescript/issues/migration-introspection-bug/src/index.ts:4:14)
  private readonly _id?: ID | undefined = undefined
  private readonly _hello?: string | undefined = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
     _hello?: string,
   ) {
     super(ctx)

     this._id = _id
     this._hello = _hello
   }

  /**
   * A unique identifier for this Repro.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }
  hello = async (): Promise<string> => { // repro (../typescript/issues/migration-introspection-bug/src/index.ts:13:11)
    if (this._hello) {
      return this._hello
    }

    const ctx = this._ctx.select(
      "hello",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
}

/**
 * The root of the DAG.
 */
export class Client extends BaseClient {

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
   ) {
     super(ctx)

   }

  /**
   * Get the Raw GraphQL client.
   */
  public getGQLClient() {
    return this._ctx.getGQLClient()
  }
  repro = (source: Directory, token: Secret): Repro => { // repro (../:0:0)

    const ctx = this._ctx.select(
      "repro",
      { source, token },
    )
    return new Repro(ctx)
  }
}



async function __serveModule(): Promise<void> {
  await __dag.serveModule("/typescript/issues/migration-introspection-bug")
}

export const dag = new Client(
  new Context().withServe({ key: "repro", run: __serveModule }),
)
export function repro(source: Directory, token: Secret): Repro {
  return dag.repro(source, token)
}
