// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen entrypoint --dispatch).

import { Context, connection, getRegisteredClass } from "@dagger.io/dagger"
import { __loadObject as __loadCoreObject } from "./clients/loader.gen.js"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { Test } from "./src/index"

function rebuildTest(state: any): Test {
  const __obj = Object.assign(Object.create(Test.prototype), state ?? {})
  if (state) {
    if (state["source"] !== undefined && state["source"] !== null) {
      __obj["source"] = __loadCoreObject(state["source"], "Directory")
    }
    if (state["token"] !== undefined && state["token"] !== null) {
      __obj["token"] = __loadCoreObject(state["token"], "Secret")
    }
  }
  return __obj
}

async function serializeTest(__obj: Test): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["source"] !== undefined && (__obj as any)["source"] !== null) {
    __state["source"] = await ((__obj as any)["source"]).id()
  }
  if ((__obj as any)["token"] !== undefined && (__obj as any)["token"] !== null) {
    __state["token"] = await ((__obj as any)["token"]).id()
  }
  return __state
}



async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "Test": {
      switch (fnName) {

        case "": {
          const __arg_source = args["source"] === undefined || args["source"] === null ? args["source"] : __loadCoreObject(args["source"], "Directory")
          const __arg_token = args["token"] === undefined || args["token"] === null ? args["token"] : __loadCoreObject(args["token"], "Secret")
          const __result = await new Test(__arg_source, __arg_token) as unknown as Test
          return await serializeTest(__result)
        }

        case "hello": {
          const __parent = rebuildTest(parentJson)
          const __result = await __parent.hello()
          return __result
        }
        default:
          throw new Error(`unknown function ${fnName} on Test`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

type CallRequest = {
  receiverType: string
  receiverValue: string | null
  fnName: string
  fnArgs: string
}

async function readStdin(): Promise<string> {
  const chunks: Buffer[] = []
  for await (const chunk of process.stdin) {
    chunks.push(Buffer.from(chunk))
  }
  return Buffer.concat(chunks).toString("utf8")
}

// receiverValue and fnArgs arrive as JSON *strings*, not as embedded objects: the
// Dang entrypoint builds the request with JSON.encode, which serializes a JSON
// scalar to a string. So each is decoded a second time here.
function decodeRequest(raw: string): {
  receiverType: string
  fnName: string
  parentJson: any
  args: Record<string, any>
} {
  const request = JSON.parse(raw) as CallRequest
  return {
    receiverType: request.receiverType,
    fnName: request.fnName,
    parentJson:
      request.receiverValue === null || request.receiverValue === undefined
        ? null
        : JSON.parse(request.receiverValue),
    args: JSON.parse(request.fnArgs ?? "{}") as Record<string, any>,
  }
}

async function engineCall(): Promise<void> {
  const { receiverType, fnName, parentJson, args } = decodeRequest(await readStdin())

  await connection(
    async () => {
      // No serve here: a module is only ever reached through a `dag.<module>()`
      // call, and each generated client serves its own module before its first
      // query.
      const result = await invoke(receiverType, fnName, parentJson, args)
      process.stdout.write(
        result === undefined || result === null ? "null" : JSON.stringify(result),
      )
    },
    // stdout is the result channel now, so the session's logs go to stderr. The
    // engine reads one and streams the other; crossing them corrupts the result.
    { LogOutput: process.stderr },
  )
}

// The mode is checked rather than ignored so that a stale entrypoint — one
// generated against a different protocol — fails here with something readable
// instead of hanging on a stdin that never arrives.
async function main(): Promise<void> {
  const mode = process.argv[2]
  if (mode !== "engine-call") {
    throw new Error(`unknown mode ${JSON.stringify(mode ?? "")}; want "engine-call"`)
  }
  return engineCall()
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})