# Dagger workspace configuration
# Install modules with: dagger module install <module>
# Example:
#   dagger module install dagger.io/linux/wolfi

[modules]

[modules.deno]
source = "github.com/dagger/deno@collections"
