// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen generate-entrypoint).

import { Context, Error as DaggerError, FunctionCachePolicy, TypeDefKind, connection, dag, getRegisteredClass } from "@dagger.io/dagger"
import { __loadObject as __loadCoreObject } from "./sdk/loader.gen.js"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { Repro } from "./src/index"

function formatError(e: unknown): DaggerError {
  if (e instanceof Error) {
    let error = dag.error(e.message)
    const ext = (e as { extensions?: Record<string, unknown> }).extensions
    if (ext) {
      for (const [k, v] of Object.entries(ext)) {
        if (v !== "" && v !== undefined && v !== null) {
          error = error.withValue(
            k,
            JSON.stringify(v) as string & { __JSON: never },
          )
        }
      }
    }
    return error
  }
  try {
    return dag.error(JSON.stringify(e))
  } catch {
    return dag.error(String(e))
  }
}

function rebuildRepro(state: any): Repro {
  const __obj = Object.assign(Object.create(Repro.prototype), state ?? {})
  if (state) {
    if (state["source"] !== undefined && state["source"] !== null) {
      __obj["source"] = __loadCoreObject(state["source"], "Directory")
    }
    if (state["token"] !== undefined && state["token"] !== null) {
      __obj["token"] = __loadCoreObject(state["token"], "Secret")
    }
  }
  return __obj
}

async function serializeRepro(__obj: Repro): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["source"] !== undefined && (__obj as any)["source"] !== null) {
    __state["source"] = await ((__obj as any)["source"]).id()
  }
  if ((__obj as any)["token"] !== undefined && (__obj as any)["token"] !== null) {
    __state["token"] = await ((__obj as any)["token"]).id()
  }
  return __state
}



async function register(): Promise<string> {
  let mod = dag.module_()
  let obj_Repro = dag.typeDef().withObject("Repro", { sourceMap: dag.sourceMap("src/index.ts", 4, 14) })
  obj_Repro = obj_Repro.withFunction(dag.function_("hello", dag.typeDef().withKind(TypeDefKind.StringKind)).withSourceMap(dag.sourceMap("src/index.ts", 13, 11)))
  obj_Repro = obj_Repro.withConstructor(dag.function_("", obj_Repro).withArg("source", dag.typeDef().withObject("Directory"), { sourceMap: dag.sourceMap("src/index.ts", 8, 15) }).withArg("token", dag.typeDef().withObject("Secret"), { sourceMap: dag.sourceMap("src/index.ts", 8, 34) }))
  mod = mod.withObject(obj_Repro)
  return await mod.id()
}

async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "Repro": {
      switch (fnName) {

        case "": {
          const __arg_source = args["source"] === undefined || args["source"] === null ? args["source"] : __loadCoreObject(args["source"], "Directory")
          const __arg_token = args["token"] === undefined || args["token"] === null ? args["token"] : __loadCoreObject(args["token"], "Secret")
          const __result = await new Repro(__arg_source, __arg_token) as unknown as Repro
          return await serializeRepro(__result)
        }

        case "hello": {
          const __parent = rebuildRepro(parentJson)
          const __result = await __parent.hello()
          return __result
        }
        default:
          throw new Error(`unknown function ${fnName} on Repro`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

async function dispatch() {
  await connection(async () => {
    const fnCall = dag.currentFunctionCall()
    const parentName = await fnCall.parentName()

    if (parentName === "") {
      const id = await register()
      await fnCall.returnValue(JSON.stringify(id) as string & { __JSON: never })
      return
    }

    const fnName = await fnCall.name()
    const parentJson = JSON.parse(await fnCall.parent())
    const fnArgs = await fnCall.inputArgs()

    const args: Record<string, any> = {}
    for (const arg of fnArgs) {
      args[await arg.name()] = JSON.parse(await arg.value())
    }

    try {
      const result = await invoke(parentName, fnName, parentJson, args)
      const out = result === undefined || result === null ? "null" : JSON.stringify(result)
      await fnCall.returnValue(out as string & { __JSON: never })
    } catch (e: unknown) {
      await fnCall.returnError(formatError(e))
      process.exit(1)
    }
  }, { LogOutput: process.stdout })
}

dispatch().catch((e) => {
  console.error(e)
  process.exit(2)
})